### ISSUE TITLE
为什么移动端使用,选项字体变很得模糊呢

### ISSUE THREAD

**Issue by xiaomocqk** [laden666666/my-picker#2]

**Comment by laden666666** [comment]
因为文字被放大了。而且很抱歉，这个项目还未完成，很多问题没有解决，我也暂时没精力完成它T_T。

**Comment by laden666666** [comment]
大概下个月，我会把这个项目完成，发布一个Beta版。

**Comment by laden666666** [comment]
这个问题并不好解决，根据stackoverflow的[一些方法](https://stackoverflow.com/questions/8024061/webkit-blurry-text-with-css-scale-translate3d)可以减缓模糊的程度，但是会引入其他的问题

目前正在做火狐和ie的兼容，这个过程中再看看有没有好的方法解决这个模糊的问题。

**Comment by laden666666** [comment]
使用`text-shadow: 0 0px #040404, 0px 0 black, 0px 0 black, 0 0px black;`将模糊问题减轻。虽然仍然存在模糊问题，但是已经不影响使用了。
事实上即使不使用text-shadow在分辨率较高的显示器上，几乎感觉不到模糊问题。但是在分辨率较低的屏幕上字体显示非常模糊。加上text-shadow有了明显改善

**Comment by laden666666** [comment]
在v1.0.0版本中，使用zoom属性，对迷糊问题做了进一步优化。在不支持zoom属性的浏览器中（如狐火），仍然有轻微模糊，但是不影响使用。而在支持zoom属性的浏览器中，模糊问题得到了更完善的解决
