### ISSUE TITLE
main.js里面引入有问题

### ISSUE THREAD

**Issue by hongtao2013** [laden666666/my-picker#3]
require('./../dist/picker.css');
module.exports = require('./../dist/picker');
这样引入总是报错，应该是引入my-picker

**Comment by laden666666** [comment]
main.js是用npm引入时候用的，这种方式用的话确实不该引入picker.css。因为我工程使用的webpack，支持require来引用css文件，所以没注意到这个问题。
```
require('my-picker');
```
如果是在nodejs中如上边那样调用，这样确实会报错。

下个月我会更新一个版本，而且会把这个项目放到npm上，到时候会解决这个引用问题的

**Comment by laden666666** [comment]
项目已经部署到npm上面了，请根据文档重新即可解决问题
### 浏览器环境
浏览器环境直接导入dist下的**my-picker.js**和**my-picker.css**文件即可

### webpack环境
执行cli命令
```
npm i my-picker -S
```

并在js文件中引用
```
import myPicker form 'my-picker'
import 'my-picker/my-picker.css'
```
