### ISSUE TITLE
Uncaught (in promise) AbortError: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22 at datePicker.html : 0

### ISSUE THREAD

**Issue by asher-fire** [laden666666/my-picker#5]
Uncaught (in promise) AbortError: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22 at datePicker.html : 0

**Comment by asher-fire** [comment]
多次快速切换回出现这个问题

**Comment by asher-fire** [comment]
这个是音频问题。我把音频代码暂时屏蔽，就没有这个问题了。

**Comment by laden666666** [comment]
@zds-jack 请问你是在什么平台上面发现的问题？我在ios和安卓平台上发现了[不能播放音频文件的问题](https://github.com/laden666666/my-picker/issues/4)，但是不影响用户选择，而且这个问题我会在近期修复。
在pc平台上面，各种浏览器均未发现音频文件播放的问题。
屏蔽音频播放是有[配置项](https://github.com/laden666666/my-picker/blob/master/docs/doc.md#hasvoice)的，无需修改源码。

**Comment by zds-jack** [comment]
我用的是红米note4x,android 7.0

**Comment by asher-fire** [comment]
@laden666666  我用的是红米note4x,android 7.0。就是滑动快了，会有这个问题

**Comment by asher-fire** [comment]
@laden666666 我们公司有一个老android4.4.4 的机子，那个上面跑不了这个，首先会有一个syboml的函数不识别错误，修复以后，也无法使用。这个最低兼容到android和ios版本多少

**Comment by laden666666** [comment]
@zds-jack syboml很早以前用了，后来用ts重写的时候移除了全部的syboml，我今晚检查一下代码，看看还有没有没移除的syboml。
针对现在的版本，可以加入cone-js或babel-polyfill解决syboml的问题

**Comment by laden666666** [comment]
代码没有Symbol了，一些Symbol是ts和babel编译产生的，但是不会抛错的。

**Comment by asher-fire** [comment]
@laden666666 我是从https://laden666666.github.io/my-picker/ 
![ea3138f62f744bb210c0d1c731d5290](https://user-images.githubusercontent.com/16936239/41453849-dc2aefd2-70a9-11e8-9b95-5d3392bcbb05.png)

这里点击的下载选项，然后跳转到了https://github.com/laden666666/my-picker/releases/tag/0.0.1 
![ded9f10dd62b33184c5888e838209e3](https://user-images.githubusercontent.com/16936239/41453786-9dc5fe3a-70a9-11e8-995b-7861e089ed95.png)
 当时下载的时候，没有太注意，就直接下载了0.0.1 版本。希望修改一下下载路径，指向最新版本

**Comment by laden666666** [comment]
文档错误已经改正了，请下载最新版本，0.0.1是第一个版本，问题很多
