### ISSUE TITLE
安卓4.4上跑不了

### ISSUE THREAD

**Issue by asher-fire** [laden666666/my-picker#6]
安卓4.4上跑不了

**Comment by laden666666** [comment]
当前版本（0.1.4）及更早版本中，不支持Android5以下的默认浏览器，因为Android5以下的3d效果太卡，导致选择器完全不能使用。当前版本为了兼容ie提供了一个非3d的选择面板，当发现浏览器不支持或者不适合使用3d选择面板的时候，会强制切换到非3d选择面板，当前版面没做对Android5以下浏览器的兼容，下一个版本会兼容。

**Comment by asher-fire** [comment]
好的，期待中

**Comment by laden666666** [comment]
上周发布了v0.1.5版本，已对安卓4.2和4.4兼容，当时由于没有测试机所以未测试；今天测试完成，安卓4.2和4.4都可用。后续会补充一个兼容性的表格和英文文档

**Comment by asher-fire** [comment]
@laden666666  虽然能用了，但是有比较明显的缓慢，感觉不如android5+版本流畅。
