### ISSUE TITLE
这个包是不是太大了 这个有影响吗

### ISSUE THREAD

**Issue by xiaodao868** [laden666666/my-picker#8]
这个包是不是太大了 这个有影响吗

**Comment by laden666666** [comment]
js的min文件大小是39.4 KB，这个大小还可以吧，其实控件本身不是很大，可能是里面内置了一个base64的mp3文件，用来做tick声，使得打出的包比较大。我也用了AudioContext代替mp3文件实现音效，但是为了兼容性，mp3文件还是保留了。如果你认为有必要降低文件的大小，我会考虑仅用AudioContext实现tick声，去掉mp3文件，这样js的min文件应该会小不少，但是这样一部分浏览器将没有tick音效。
